# Generated by Django 4.0.6 on 2022-08-21 12:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_avatar_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=users.models.Profile.change_avatar_name),
        ),
    ]
