# Generated by Django 4.0.6 on 2023-02-10 20:53

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=users.models.LongerImageField(default='default.jpg', max_length=2048, upload_to=users.models.Profile.change_avatar_name),
        ),
    ]
