version: "3.9"

services:
  pgdb:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: unless-stopped
  
  web:
    container_name: django
    build: .
    command: >
      sh -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:3000"
    env_file:
      - ./.env
    environment:
      - DEV=False
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
volumes:
  postgres_data:
