# Generated by Django 4.0.6 on 2022-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
