# Generated by Django 4.0.6 on 2022-08-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_link_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='link_count',
        ),
    ]
