# Generated by Django 4.0.6 on 2022-08-20 13:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_link_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#29292D', image_field=None, max_length=18, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('card_color', colorfield.fields.ColorField(default='#A5C9CA', image_field=None, max_length=18, samples=None)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='LinkDecorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#29292D', image_field=None, max_length=18, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.link')),
            ],
        ),
    ]
