# Generated by Django 4.0.6 on 2022-08-20 17:23

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagedecorator_linkdecorator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdecorator',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decorator', to='pages.link'),
        ),
        migrations.AlterField(
            model_name='pagedecorator',
            name='background_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='pagedecorator',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decorator', to='pages.page'),
        ),
    ]
