# Generated by Django 4.0.6 on 2022-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_linkdecorator_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedecorator',
            name='show_date',
            field=models.BooleanField(default=True),
        ),
    ]
